---
updates:
  - allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    directory: "/"
    open-pull-requests-limit: 10
    package-ecosystem: "bundler"
    schedule:
      interval: "daily"
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
version: 2
