---

inherit_gem:
  rubocop-rails_config:
    - "config/rails.yml"

AllCops:
  Exclude:
    - 'gemfiles/*'
    - 'gemfiles/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: "2.7"

Layout/CaseIndentation:
  EnforcedStyle: "end"

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: "around"

Layout/EndOfLine:
  EnforcedStyle: "lf"

Layout/IndentationConsistency:
  EnforcedStyle: "normal"

Style/StringLiterals:
  EnforcedStyle: "single_quotes"
