---
jobs:
  release-please:
    outputs:
      release_created: "${{ steps.release.outputs.release_created }}"
      tag_name: "${{ steps.release.outputs.tag_name }}"
      version_number: "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
    permissions:
      contents: "write"
      issues: "write"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      - id: "release"
        uses: "googleapis/release-please-action@v4"

  release:
    if: "${{ needs.release-please.outputs.release_created }}"
    name: "Release"
    needs:
      - "release-please"
    permissions:
      id-token: "write"
      contents: "write"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "ruby/setup-ruby@v1"
        with:
          bundler-cache: true
      - uses: "rubygems/release-gem@v1"

name: "Release"

"on":
  push:
    branches:
      - "main"
