---
jobs:
  github_packages:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v1"
      - uses: "actions/setup-ruby@v1"
        with:
          ruby-version: "2.7"
      - name: "Publish to GitHub"
        uses: "jstastny/publish-gem-to-github@v1.1"
        with:
          owner: "envylabs"
          token: "${{ secrets.GITHUB_TOKEN }}"
name: "Release"
"on":
  push:
    tags:
      - "v*"
