---
jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "ruby/setup-ruby@v1"
        with:
          bundler-cache: "true"
          ruby-version: "2.7"
      - name: "Run Tests"
        run: "bundle exec rake spec"
      - name: "Check Ruby Style"
        run: "bundle exec rubocop -c ./.rubocop.yml -fq"
      - name: "Check Licenses"
        run: |
          # Forcibly set Bundler platform to patch for https://github.com/pivotal/LicenseFinder/issues/828
          bundle config --local deployment false
          bundle lock --add-platform x86_64-linux
          bundle config --local deployment true

          bundle exec license_finder --quiet
    strategy:
      matrix:
        gemfile:
          - "Gemfile"
          - "gemfiles/faraday_latest.gemfile"
          - "gemfiles/faraday_0.8.gemfile"
          - "gemfiles/faraday_0.x.gemfile"
          - "gemfiles/faraday_1.x.gemfile"
name: "Tests"
"on":
  - "push"
