---
jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v1"
      - uses: "actions/setup-ruby@v1"
        with:
          ruby-version: "2.7"
      - uses: "actions/cache@v1"
        with:
          key: "${{ runner.os }}-gems-${{ hashFiles(matrix.gemfile) }}"
          path: "vendor/bundle"
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: "Install Latest Bundler"
        run: |
          gem install bundler --no-document
          bundle config --global gemfile ${{ matrix.gemfile }}
          bundle config path vendor/bundle
          bundle config set without "tools benchmarks docs"
      - name: "Bundle Install"
        run: "bundle install --jobs 4 --retry 3"
      - name: "Run Tests"
        run: "bundle exec rake spec"
      - name: "Check Licenses"
        run: "bundle exec license_finder --quiet"
      - name: "Check Ruby Style"
        run: "bundle exec rubocop -c ./.rubocop.yml -fq"
    strategy:
      matrix:
        gemfile:
          - "Gemfile"
          - "gemfiles/faraday_latest.gemfile"
          - "gemfiles/faraday_0.8.gemfile"
          - "gemfiles/faraday_0.x.gemfile"
          - "gemfiles/faraday_1.x.gemfile"
name: "Tests"
"on":
  - "push"
